### PR TITLE
DIG-1523: Update NodeJS and round field level completeness 

### PR DESCRIPTION
**Pull request by mshadbolt**
## Ticket(s)

- [DIG-1523](https://candig.atlassian.net/browse/DIG-1523)

## Description

- Update NodeJS to latest 21.7.0 which incorporates updated npm version 10.5.0
- Round field level completeness for neater display

## Screenshots (if appropriate)

Uploaded data is from the small synthetic dataset: https://github.com/CanDIG/mohccn-synthetic-data

### Before PR

Screenshot 2024-03-06 at 5 18 55 PM

### After PR

Screenshot 2024-03-08 at 10 35 38 AM

## Types of Change(s)

-   [x] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [ ] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [ ] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

[DIG-1523]: https://candig.atlassian.net/browse/DIG-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mshadbolt** [comment]
Seems like the node/npm update may have broken the patient info view, kicking this one back to draft. Could also be that the data has more null values/missing objects and this is causing the info to error

**Comment by mshadbolt** [comment]
rounding was incorporated into [PR#129](https://github.com/CanDIG/candig-data-portal/pull/129)

Not sure if we still want to do this node upgrade?

**Comment by OrdiNeu** [comment]
I think the node version was incorporated into that PR as well -- it looks like it was rebased off of this one. In any case, this built successfully for me :heavy_check_mark:

**Comment by CourtneyGosselin** [comment]
I did test and rebase off this branch, but I didn't end up putting the newer node version on my branch.

**Review by CourtneyGosselin — APPROVED** [review]
LGTM!

**Comment by mshadbolt** [comment]
this PR got messy so going to make a new on with just the node update

**Pull request closed without merging**
