### PR TITLE
DIG-1640: Data-portal: Timeline bugs -- highlight folders, age at death, and clickable single dates

### PR DESCRIPTION
**Pull request by OrdiNeu**
## Ticket(s)

- [DIG-1640](https://candig.atlassian.net/browse/DIG-1640)

## Description

Fixes to:
- age at death
- highlighting folders
- clickable single dates

+ A lot of refactoring

### After PR

[Screencast from 2024-06-27 02:59:07 PM.webm](https://github.com/CanDIG/candig-data-portal/assets/4656440/c2f3f9e3-d7f1-43f2-ace0-2106f33a3fc6)

## Types of Change(s)

-   [x] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [ ] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [ ] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [x] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

[DIG-1640]: https://candig.atlassian.net/browse/DIG-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CourtneyGosselin — CHANGES_REQUESTED** [review]
To summarize our conversation in direct messages:

The tooltips on the timeline should have the date intervals changed to match the grain of the folder section. Instead of displaying "treatment start 14 Year(s) old end 18 year(s) old," it should display "14y 3m 2d" and "18y 7m 17d."

Another error found is that the follow-up and specimen options do not select the folders or change the table. This issue causes the table to appear blank. Testing was done on cohort SYN-2 with DONOR_7.

**Comment by OrdiNeu** [comment]
Should look like this now:
image

Also the click events for the follow ups I could find have been fixed, and I fixed Biomarkers which broke inadvertently

**Review by CourtneyGosselin — CHANGES_REQUESTED** [review]
Looks really good. One lingering problem is with the follow-up sections, and I would assume any sections with duplicate names. The table updates, but the folder doesn't highlight. Specimen works now though. Tested on Synthetic-2 with Donor 7

**Review by CourtneyGosselin — APPROVED** [review]
LGTM

**Pull request merged**
