### PR TITLE
DIG-1085: Sidebar and search

### PR DESCRIPTION
**Pull request by OrdiNeu**
## Ticket(s)
[DIG-1085](https://candig.atlassian.net/browse/DIG-1085)
[DIG-1091](https://candig.atlassian.net/browse/DIG-1091)

## Description
This implements the sidebar, and fixes up a few of the bugs introduced by #80 . Though this doesn't yet include the finished genomic search, it does do the query.

## Expected Behaviour
The sidebar is now available for search.

### After PR
image

## Types of Change(s)
- [ ] 🪲 Bug fix (non-breaking change that fixes an issue)
- [x ] ✨ New feature (non-breaking change that adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:
- [x] Prettier linter doesn't return errors
- [x] Locally tested

[DIG-1085]: https://candig.atlassian.net/browse/DIG-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIG-1091]: https://candig.atlassian.net/browse/DIG-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by SonQBChau** [comment]
Issue:

Sidebar is hidden but still occupies space on the summary page
 
Screenshot 2023-07-20 at 2 58 07 PM

**Comment by SonQBChau** [comment]
Issue:

I got an error in the console on the summary page

```
react-jsx-dev-runtime.development.js:118 Warning: Failed prop type: The prop `dropDown` is marked as required in `CustomOfflineChart`, but its value is `undefined`.
    at CustomOfflineChart (http://candig-dev.hpc4healthlocal:5080/static/js/src_store_api_js-src_ui-component_LoadingIndicator_LoadingIndicator_js-src_views_summary_Cust-021a37.chunk.js:423:5)
    at Summary (http://candig-dev.hpc4healthlocal:5080/static/js/src_views_summary_summary_js.chunk.js:840:81)
    at Suspense
    at Outlet (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:147769:26)
    at main
    at SidebarProvider (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:2974:5)
    at div
    at MainLayout (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:3408:19)
    at ThemeRoutes (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:4190:69)
    at NavigationScroll (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:3657:5)
    at StyledEngineProvider (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:30561:5)
    at InnerThemeProvider (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:31533:70)
    at ThemeProvider (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:30376:5)
    at ThemeProvider (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:31553:5)
    at App (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:662:81)
    at Router (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:147794:15)
    at BrowserRouter (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:146604:5)
    at SearchResultsProvider (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:7107:62)
    at Provider (http://candig-dev.hpc4healthlocal:5080/static/js/bundle.js:144044:20)
```

**Comment by SonQBChau** [comment]
Issue:
Navigation bar floats through the page
Screenshot 2023-07-20 at 3 02 43 PM

Screenshot 2023-07-20 at 3 36 15 PM

**Comment by SonQBChau** [comment]
Issue:
all the boxes are cut off are misaligned:
Screenshot 2023-07-20 at 3 04 33 PM

**Comment by SonQBChau** [comment]
Issue:
Kinda unclear what 4 and 7.69% here represent for 
Screenshot 2023-07-20 at 3 07 15 PM

**Comment by SonQBChau** [comment]
Issue:
On Safari with cookies disabled by default, cannot access our site:
Screenshot 2023-07-20 at 3 11 43 PM

**Comment by SonQBChau** [comment]
Issue:
Inactive for 5 mins would break the site, either a white screen of death or js calling failures

**Comment by OrdiNeu** [comment]
> Issue: On Safari with cookies disabled by default, cannot access our site: 

We'll need to swap out how keycloak functions, or something? Unsure if there's an update or something that'll handle this, but this is outside the scope of this PR


> Issue: Inactive for 5 mins would break the site, either a white screen of death or js calling failures

Sounds like the cookie is expiring... We could create a sentinel check to make sure that the Keycloak cookie is still active, but that's outside the scope of this PR.

Most of the other comments have now been addressed :heavy_check_mark:

**Review by CourtneyGosselin — APPROVED** [review]
All PR issues resolved LGTM

**Pull request merged**
