### PR TITLE
C3G icon added.

### PR DESCRIPTION
**Pull request by DavidBrownlee**
## Ticket(s)

-

## Description
Includes C3G icon in top right of data portal home.
-

## Expected Behaviour

-

## Related Issues (if appropriate)

-

## To do/Tickets to be made before merging branch

-

## Types of Change(s)

-   [ ]  Bug fix (non-breaking change that fixes an issue)
-   [  ✨ ] New feature (non-breaking change that adds functionality)
-   [ ]  Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [ ] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [ *** ] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch

### CODE REVIEW

**Review by CourtneyGosselin — CHANGES_REQUESTED** [review]
There are multiple ESLint errors in this pull request, and you can readily identify them in both the changed files and the GitHub Actions logs. It's important to inspect for warnings, even if they appear as checkmarks in github actions since warnings won't fail. Merging the 'develop' branch into the current one may address some of these issues. Moreover, we are working towards a process of adding logos at the site instead of the repository. In the future, once the configuration for logo setup is finalized at the site, you can follow the instructions provided for production builds.

**Comment by DavidBrownlee** [comment]
Thank you for the feedback.  The linting errors will take more investigation.

Adding a logo for a new site currently only requires 3 lines of code in one file and a .env entry. Considering that this will be a very infrequent operation, why change the process?

**Comment by CourtneyGosselin** [comment]
CanDIG is currently hosted individually at each location. To improve efficiency, we're updating the logo addition process: instead of directly adding logos to the repo, administrators will host them on their server and include the image path in their .env. Logos can then be incorporated through the CanDIGv2 environment and configured in the front-end's config.js file. This adjustment is part of our technical debt tickets, scheduled for addressing during one of our tech debt weeks soon. The change will remove the requirement for sites to add to a microservice during spin-up or push to Git before usage, simplifying the process for administrators.

**Comment by DavidBrownlee** [comment]
Okay, any site-specific change that can be reduced to the .env file sounds great to me.
Hooray for technical debt weeks!

I withdraw this PR.

**Pull request closed without merging**
