### PR TITLE
DIG-1639: Discovery queries fail when navigating to subsequent page of clinical data results

### PR DESCRIPTION
**Pull request by OrdiNeu**
## Ticket(s)

- [DIG-1639](https://candig.atlassian.net/browse/DIG-1639)

## Description

- Going to page 2 of search results causes all of the discovery queries to fail, because the discovery queries don't really handle the page/page_size parameter. This cleans the request of that before sending it off.

## Expected Behaviour

- Going to page 2 does not blank out the discovery charts.

## Types of Change(s)

-   [x] 🪲 Bug fix (non-breaking change that fixes an issue)
-   [ ] ✨ New feature (non-breaking change that adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## Has it been tested for:

-   [ ] My change requires a change to the documentation
-   [ ] I have updated the documentation accordingly
-   [ ] Prettier linter doesn't return errors
-   [ ] Production branch PR browser testing: Chrome, Firefox, Edge, etc.
-   [ ] Locally tested
-   [ ] Dev server tested
-   [ ] Production tested when merging into stable/production branch
-   [ ] [Runbook tasks](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) pass locally/on UHN-Dev
-   [ ] If visuals have changed, [Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) has been updated with new screenshots

[DIG-1639]: https://candig.atlassian.net/browse/DIG-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mshadbolt — COMMENTED** [review]
Ingested small dataset and navigated to second page and discovery query graphs kept working. 

Seems to be intermittently not working as expected

I gave user2 access to SYNTHETIC-1. I selected Estradiol as hormone therapy. The table says <5 donors, the clinical data table says 1 donor, the distribution of cohort by node says 6 donors

Screenshot 2024-06-10 at 3 09 00 PM

Or if I select chemotherapy as treatment, is says <5 donors for each program but the cohort by node is displaying the full number of donors per cohort, even though there is the message indicating it should be censored

Screenshot 2024-06-10 at 3 11 43 PM

**Comment by OrdiNeu** [comment]
@mshadbolt 

> Seems to be intermittently not working as expected 

After merging in Courtney's loading indicator, it seems to now force the graphs to update as needed. I gave it a quick runthrough after merging and it looks like it's now fixed.

**Comment by mshadbolt** [comment]
I confirmed that the original issue with the graphs not working on subsequent pages was fixed but found a bug where the pagination is not showing accurately. On the first page it is correct, showing 1-10 of 13, but when I click the arrow to go to the next page, the display in the clinical data updates to show the last 3 donors, 11-13 of 13, but the counter at the bottom is still showing 1-10 of 13, and you can't click the left arrow to go back to the first 10 donors because the arrow is greyed out. Clicking the right arrow does then change the display to 11-13 of 13, then you can click the left arrow to go back to the first 10 donors. Not sure if the loader is getting in the way of things? I noticed that the loading spinner shows up when you first click the right arrow to go to the last 3 donors, but not the second time when the display is shown accurately. Also not super sure why all the visualisations go blank with the loading spinner when it is only the clinical data table that is getting updated (also not sure whether it is actually necessary to show a loading spinner to go the next page of the table?)

Screenshot 2024-06-19 at 2 12 27 PM

**Comment by OrdiNeu** [comment]
> I confirmed that the original issue with the graphs not working on subsequent pages was fixed but found a bug where the pagination is not showing accurately. 

Oh, I had checked that the graph was fixed after merging the spinners, but forgot to check the behaviour of the table. I put in a fix in [0afb15b](https://github.com/CanDIG/candig-data-portal/pull/160/commits/0afb15b09df4d536a7f917f32be592f8eb468797) but let me run through the runbook

**Review by mshadbolt — APPROVED** [review]
tested and confirmed this is working for me now

**Pull request merged**
